version: '3'

services:
  node:
    build:
      context: ../
      dockerfile: docker/Dockerfile.production
    environment:
      NODE_ENV: 'production'
      VIRTUAL_HOST: 'epps-apps.com'
      LETSENCRYPT_HOST: 'epps-apps.com'
      LETSENCRYPT_EMAIL: 'info@epps-apps.com'
      ALLOW_ACCESS_FROM: 'https://epps-apps.com'
    volumes:
      - ./scripts/:/usr/src/app/scripts/
      - ./build/:/usr/src/app/build/

networks:
  default:
    external:
      name: webproxy
