version: '3'

services:
  node:
    build:
      context: ../
      dockerfile: docker/Dockerfile.development
    environment:
      VIRTUAL_HOST: 'epps-apps-backend.test'
      NODE_ENV: 'development'
    volumes:
    - ../src:/usr/src/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    external: true
    name: 'local_network'
